services:
  stars_bot:
    build: .
    container_name: stars_bot
    restart: unless-stopped
    env_file: .env
    expose:
      - "8000"
    networks:
      deploy_default:
        aliases:
          - stars_bot
          - bot
          - stars
          - starsbot

networks:
  deploy_default:
    external: true
