services:
  - type: web
    name: referalbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /webhook
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: DB_PATH
        value: bot.db
